spring:
  application:
    name: ditto-trip

  datasource:
    url: jdbc:mysql://localhost:3306/dittotrip?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false